# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_V0Mh8_boE1Xkz7GLfY1vLCJPPBm1tFR
"""

import requests

API_KEY = "your_tmdb_api_key"  # Replace with your TMDb API Key

def get_movies_by_genre(genre):
    """Fetches movies based on genre from TMDb API."""
    url = f"https://api.themoviedb.org/3/discover/movie?api_key={5fec0affb3191a8e860dd4017044c0f8}&with_genres={genre}"
    response = requests.get(url)
    if response.status_code == 200:
        movies = response.json().get("results", [])
        return movies[:10]  # Return top 10 movies
    return []

def search_movies(query):
    """Searches for movies based on user query."""
    url = f"https://api.themoviedb.org/3/search/movie?api_key={5fec0affb3191a8e860dd4017044c0f8}&query={query}"
    response = requests.get(url)
    if response.status_code == 200:
        movies = response.json().get("results", [])
        return movies[:5]  # Return top 5 matches
    return []