# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_V0Mh8_boE1Xkz7GLfY1vLCJPPBm1tFR
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
import pickle

# Sample dataset (expand this with real data)
data = {
    "prompt": ["I want a scary horror movie", "A fun animated movie", "A thrilling action-packed film"],
    "genre": ["Horror", "Animation", "Action"]
}

df = pd.DataFrame(data)

# Training a simple model
X = df["prompt"]
y = df["genre"]

pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", LogisticRegression())
])

pipeline.fit(X, y)

# Save model
with open("genre_model.pkl", "wb") as f:
    pickle.dump(pipeline, f)

# Function to predict genre
def predict_genre(prompt):
    with open("genre_model.pkl", "rb") as f:
        model = pickle.load(f)
    return model.predict([prompt])[0]