# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_V0Mh8_boE1Xkz7GLfY1vLCJPPBm1tFR
"""

from transformers import pipeline
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Download NLTK resources
nltk.download("punkt")
nltk.download("stopwords")

# Sentiment Analysis using a pre-trained transformer model
sentiment_pipeline = pipeline("sentiment-analysis")

def extract_mood(prompt):
    """Extracts mood using sentiment analysis."""
    result = sentiment_pipeline(prompt)[0]
    return result["label"]

def extract_keywords(prompt):
    """Extracts keywords from the user input to determine genre and meaning."""
    words = word_tokenize(prompt.lower())
    filtered_words = [word for word in words if word.isalnum() and word not in stopwords.words("english")]
    return filtered_words